// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { GanttChartAPI } from './ganttchart-api';
import { GanttChartDB } from './ganttchart-db';

@Injectable({
  providedIn: 'root'
})
export class GanttChartService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  GanttChartServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ganttchartsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggooglecharts/go/v1/ganttcharts';

  constructor(
    private http: HttpClient
  ) { }

  /** GET ganttcharts from the server */
  getGanttCharts(): Observable<GanttChartDB[]> {
    return this.http.get<GanttChartDB[]>(this.ganttchartsUrl)
      .pipe(
        tap(_ => this.log('fetched ganttcharts')),
        catchError(this.handleError<GanttChartDB[]>('getGanttCharts', []))
      );
  }

  /** GET ganttchart by id. Will 404 if id not found */
  getGanttChart(id: number): Observable<GanttChartDB> {
    const url = `${this.ganttchartsUrl}/${id}`;
    return this.http.get<GanttChartDB>(url).pipe(
      tap(_ => this.log(`fetched ganttchart id=${id}`)),
      catchError(this.handleError<GanttChartDB>(`getGanttChart id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new ganttchart to the server */
  postGanttChart(ganttchartAPI: GanttChartAPI): Observable<GanttChartDB> {
    return this.http.post<GanttChartDB>(this.ganttchartsUrl, ganttchartAPI, this.httpOptions).pipe(
      tap((newGanttChart: GanttChartDB) => {})
    );
  }

  /** DELETE: delete the ganttchartdb from the server */
  deleteGanttChart(ganttchartdb: GanttChartDB | number): Observable<GanttChartDB> {
    const id = typeof ganttchartdb === 'number' ? ganttchartdb : ganttchartdb.ID;
    const url = `${this.ganttchartsUrl}/${id}`;

    return this.http.delete<GanttChartDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted ganttchartdb id=${id}`)),
      catchError(this.handleError<GanttChartDB>('deleteGanttChart'))
    );
  }

  /** PUT: update the ganttchartdb on the server */
  updateGanttChart(ganttchartdb: GanttChartDB): Observable<GanttChartDB> {
    const id = typeof ganttchartdb === 'number' ? ganttchartdb : ganttchartdb.ID;
    const url = `${this.ganttchartsUrl}/${id}`;

    // insertion point for reset of reverse pointers (to avoid circular JSON)
    ganttchartdb.Tasks = []

    return this.http.put(url, ganttchartdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated ganttchartdb id=${ganttchartdb.ID}`)
      }),
      catchError(this.handleError<GanttChartDB>('updateGanttChart'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
