// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { RessourceAPI } from './ressource-api';
import { RessourceDB } from './ressource-db';

@Injectable({
  providedIn: 'root'
})
export class RessourceService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  RessourceServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private ressourcesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggooglecharts/go/v1/ressources';

  constructor(
    private http: HttpClient
  ) { }

  /** GET ressources from the server */
  getRessources(): Observable<RessourceDB[]> {
    return this.http.get<RessourceDB[]>(this.ressourcesUrl)
      .pipe(
        tap(_ => this.log('fetched ressources')),
        catchError(this.handleError<RessourceDB[]>('getRessources', []))
      );
  }

  /** GET ressource by id. Will 404 if id not found */
  getRessource(id: number): Observable<RessourceDB> {
    const url = `${this.ressourcesUrl}/${id}`;
    return this.http.get<RessourceDB>(url).pipe(
      tap(_ => this.log(`fetched ressource id=${id}`)),
      catchError(this.handleError<RessourceDB>(`getRessource id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new ressource to the server */
  postRessource(ressourceAPI: RessourceAPI): Observable<RessourceDB> {
    return this.http.post<RessourceDB>(this.ressourcesUrl, ressourceAPI, this.httpOptions).pipe(
      tap((newRessource: RessourceDB) => {})
    );
  }

  /** DELETE: delete the ressourcedb from the server */
  deleteRessource(ressourcedb: RessourceDB | number): Observable<RessourceDB> {
    const id = typeof ressourcedb === 'number' ? ressourcedb : ressourcedb.ID;
    const url = `${this.ressourcesUrl}/${id}`;

    return this.http.delete<RessourceDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted ressourcedb id=${id}`)),
      catchError(this.handleError<RessourceDB>('deleteRessource'))
    );
  }

  /** PUT: update the ressourcedb on the server */
  updateRessource(ressourcedb: RessourceDB): Observable<RessourceDB> {
    const id = typeof ressourcedb === 'number' ? ressourcedb : ressourcedb.ID;
    const url = `${this.ressourcesUrl}/${id}`;

    // insertion point for reset of reverse pointers (to avoid circular JSON)

    return this.http.put(url, ressourcedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated ressourcedb id=${ressourcedb.ID}`)
      }),
      catchError(this.handleError<RessourceDB>('updateRessource'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
