// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TaskUseAPI } from './taskuse-api';
import { TaskUseDB } from './taskuse-db';

@Injectable({
  providedIn: 'root'
})
export class TaskUseService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TaskUseServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private taskusesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggooglecharts/go/v1/taskuses';

  constructor(
    private http: HttpClient
  ) { }

  /** GET taskuses from the server */
  getTaskUses(): Observable<TaskUseDB[]> {
    return this.http.get<TaskUseDB[]>(this.taskusesUrl)
      .pipe(
        tap(_ => this.log('fetched taskuses')),
        catchError(this.handleError<TaskUseDB[]>('getTaskUses', []))
      );
  }

  /** GET taskuse by id. Will 404 if id not found */
  getTaskUse(id: number): Observable<TaskUseDB> {
    const url = `${this.taskusesUrl}/${id}`;
    return this.http.get<TaskUseDB>(url).pipe(
      tap(_ => this.log(`fetched taskuse id=${id}`)),
      catchError(this.handleError<TaskUseDB>(`getTaskUse id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new taskuse to the server */
  postTaskUse(taskuseAPI: TaskUseAPI): Observable<TaskUseDB> {
    return this.http.post<TaskUseDB>(this.taskusesUrl, taskuseAPI, this.httpOptions).pipe(
      tap((newTaskUse: TaskUseDB) => {})
    );
  }

  /** DELETE: delete the taskusedb from the server */
  deleteTaskUse(taskusedb: TaskUseDB | number): Observable<TaskUseDB> {
    const id = typeof taskusedb === 'number' ? taskusedb : taskusedb.ID;
    const url = `${this.taskusesUrl}/${id}`;

    return this.http.delete<TaskUseDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted taskusedb id=${id}`)),
      catchError(this.handleError<TaskUseDB>('deleteTaskUse'))
    );
  }

  /** PUT: update the taskusedb on the server */
  updateTaskUse(taskusedb: TaskUseDB): Observable<TaskUseDB> {
    const id = typeof taskusedb === 'number' ? taskusedb : taskusedb.ID;
    const url = `${this.taskusesUrl}/${id}`;

    // insertion point for reset of reverse pointers (to avoid circular JSON)
    taskusedb.Task = {}
    let _GanttChart_Tasks_reverse = taskusedb.GanttChart_Tasks_reverse
    taskusedb.GanttChart_Tasks_reverse = {}

    return this.http.put(url, taskusedb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        taskusedb.GanttChart_Tasks_reverse = _GanttChart_Tasks_reverse
        this.log(`updated taskusedb id=${taskusedb.ID}`)
      }),
      catchError(this.handleError<TaskUseDB>('updateTaskUse'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
