// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { TaskAPI } from './task-api';
import { TaskDB } from './task-db';

@Injectable({
  providedIn: 'root'
})
export class TaskService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  TaskServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private tasksUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gonggooglecharts/go/v1/tasks';

  constructor(
    private http: HttpClient
  ) { }

  /** GET tasks from the server */
  getTasks(): Observable<TaskDB[]> {
    return this.http.get<TaskDB[]>(this.tasksUrl)
      .pipe(
        tap(_ => this.log('fetched tasks')),
        catchError(this.handleError<TaskDB[]>('getTasks', []))
      );
  }

  /** GET task by id. Will 404 if id not found */
  getTask(id: number): Observable<TaskDB> {
    const url = `${this.tasksUrl}/${id}`;
    return this.http.get<TaskDB>(url).pipe(
      tap(_ => this.log(`fetched task id=${id}`)),
      catchError(this.handleError<TaskDB>(`getTask id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new task to the server */
  postTask(taskAPI: TaskAPI): Observable<TaskDB> {
    return this.http.post<TaskDB>(this.tasksUrl, taskAPI, this.httpOptions).pipe(
      tap((newTask: TaskDB) => {})
    );
  }

  /** DELETE: delete the taskdb from the server */
  deleteTask(taskdb: TaskDB | number): Observable<TaskDB> {
    const id = typeof taskdb === 'number' ? taskdb : taskdb.ID;
    const url = `${this.tasksUrl}/${id}`;

    return this.http.delete<TaskDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted taskdb id=${id}`)),
      catchError(this.handleError<TaskDB>('deleteTask'))
    );
  }

  /** PUT: update the taskdb on the server */
  updateTask(taskdb: TaskDB): Observable<TaskDB> {
    const id = typeof taskdb === 'number' ? taskdb : taskdb.ID;
    const url = `${this.tasksUrl}/${id}`;

    // insertion point for reset of reverse pointers (to avoid circular JSON)
    taskdb.Ressource = {}
    taskdb.Dependencies = []
    let _Task_Dependencies_reverse = taskdb.Task_Dependencies_reverse
    taskdb.Task_Dependencies_reverse = {}

    return this.http.put(url, taskdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        taskdb.Task_Dependencies_reverse = _Task_Dependencies_reverse
        this.log(`updated taskdb id=${taskdb.ID}`)
      }),
      catchError(this.handleError<TaskDB>('updateTask'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
