// generated by ModelGongFileTemplate
package models

import "sort"

// swagger:ignore
type __void struct{}

// needed for creating set of instances in the stage
var __member __void

// StageStruct enables storage of staged instances
// swagger:ignore
type StageStruct struct { // insertion point for definition of arrays registering instances
	Dependencys map[*Dependency]struct{}

	GanttCharts map[*GanttChart]struct{}

	Ressources map[*Ressource]struct{}

	Tasks map[*Task]struct{}

	AllModelsStructCreateCallback AllModelsStructCreateInterface

	AllModelsStructDeleteCallback AllModelsStructDeleteInterface

	BackRepo BackRepoInterface
	
	// if set will be called before each commit to the back repo
	OnInitCommitCallback OnInitCommitInterface
}

type OnInitCommitInterface interface {
	BeforeCommit(stage *StageStruct)
}

type BackRepoInterface interface {
	Commit(stage *StageStruct)
	Checkout(stage *StageStruct)
	// insertion point for Commit and Checkout signatures
	CommitDependency(dependency *Dependency)
	CheckoutDependency(dependency *Dependency)
	CommitGanttChart(ganttchart *GanttChart)
	CheckoutGanttChart(ganttchart *GanttChart)
	CommitRessource(ressource *Ressource)
	CheckoutRessource(ressource *Ressource)
	CommitTask(task *Task)
	CheckoutTask(task *Task)
	GetLastCommitNb() uint
}

// swagger:ignore instructs the gong compiler (gongc) to avoid this particular struct
var Stage StageStruct = StageStruct{ // insertion point for array initiatialisation
	Dependencys: make(map[*Dependency]struct{}, 0),

	GanttCharts: make(map[*GanttChart]struct{}, 0),

	Ressources: make(map[*Ressource]struct{}, 0),

	Tasks: make(map[*Task]struct{}, 0),

}

func (stage *StageStruct) Commit() {
	if stage.BackRepo != nil {
		stage.BackRepo.Commit(stage)
	}
}

func (stage *StageStruct) Checkout() {
	if stage.BackRepo != nil {
		stage.BackRepo.Checkout(stage)
	}
}

// insertion point for cumulative sub template with model space calls
func (stage *StageStruct) getDependencyOrderedStructWithNameField() []*Dependency {
	// have alphabetical order generation
	dependencyOrdered := []*Dependency{}
	for dependency := range stage.Dependencys {
		dependencyOrdered = append(dependencyOrdered, dependency)
	}
	sort.Slice(dependencyOrdered[:], func(i, j int) bool {
		return dependencyOrdered[i].Name < dependencyOrdered[j].Name
	})
	return dependencyOrdered
}

// Stage puts dependency to the model stage
func (dependency *Dependency) Stage() *Dependency {
	Stage.Dependencys[dependency] = __member
	return dependency
}

// Unstage removes dependency off the model stage
func (dependency *Dependency) Unstage() *Dependency {
	delete(Stage.Dependencys, dependency)
	return dependency
}

// commit dependency to the back repo (if it is already staged)
func (dependency *Dependency) Commit() *Dependency {
	if _, ok := Stage.Dependencys[dependency]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitDependency(dependency)
		}
	}
	return dependency
}

// Checkout dependency to the back repo (if it is already staged)
func (dependency *Dependency) Checkout() *Dependency {
	if _, ok := Stage.Dependencys[dependency]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutDependency(dependency)
		}
	}
	return dependency
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of dependency to the model stage
func (dependency *Dependency) StageCopy() *Dependency {
	_dependency := new(Dependency)
	*_dependency = *dependency
	_dependency.Stage()
	return _dependency
}

// StageAndCommit appends dependency to the model stage and commit to the orm repo
func (dependency *Dependency) StageAndCommit() *Dependency {
	dependency.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMDependency(dependency)
	}
	return dependency
}

// DeleteStageAndCommit appends dependency to the model stage and commit to the orm repo
func (dependency *Dependency) DeleteStageAndCommit() *Dependency {
	dependency.Unstage()
	DeleteORMDependency(dependency)
	return dependency
}

// StageCopyAndCommit appends a copy of dependency to the model stage and commit to the orm repo
func (dependency *Dependency) StageCopyAndCommit() *Dependency {
	_dependency := new(Dependency)
	*_dependency = *dependency
	_dependency.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMDependency(dependency)
	}
	return _dependency
}

// CreateORMDependency enables dynamic staging of a Dependency instance
func CreateORMDependency(dependency *Dependency) {
	dependency.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMDependency(dependency)
	}
}

// DeleteORMDependency enables dynamic staging of a Dependency instance
func DeleteORMDependency(dependency *Dependency) {
	dependency.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMDependency(dependency)
	}
}

func (stage *StageStruct) getGanttChartOrderedStructWithNameField() []*GanttChart {
	// have alphabetical order generation
	ganttchartOrdered := []*GanttChart{}
	for ganttchart := range stage.GanttCharts {
		ganttchartOrdered = append(ganttchartOrdered, ganttchart)
	}
	sort.Slice(ganttchartOrdered[:], func(i, j int) bool {
		return ganttchartOrdered[i].Name < ganttchartOrdered[j].Name
	})
	return ganttchartOrdered
}

// Stage puts ganttchart to the model stage
func (ganttchart *GanttChart) Stage() *GanttChart {
	Stage.GanttCharts[ganttchart] = __member
	return ganttchart
}

// Unstage removes ganttchart off the model stage
func (ganttchart *GanttChart) Unstage() *GanttChart {
	delete(Stage.GanttCharts, ganttchart)
	return ganttchart
}

// commit ganttchart to the back repo (if it is already staged)
func (ganttchart *GanttChart) Commit() *GanttChart {
	if _, ok := Stage.GanttCharts[ganttchart]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitGanttChart(ganttchart)
		}
	}
	return ganttchart
}

// Checkout ganttchart to the back repo (if it is already staged)
func (ganttchart *GanttChart) Checkout() *GanttChart {
	if _, ok := Stage.GanttCharts[ganttchart]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutGanttChart(ganttchart)
		}
	}
	return ganttchart
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of ganttchart to the model stage
func (ganttchart *GanttChart) StageCopy() *GanttChart {
	_ganttchart := new(GanttChart)
	*_ganttchart = *ganttchart
	_ganttchart.Stage()
	return _ganttchart
}

// StageAndCommit appends ganttchart to the model stage and commit to the orm repo
func (ganttchart *GanttChart) StageAndCommit() *GanttChart {
	ganttchart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMGanttChart(ganttchart)
	}
	return ganttchart
}

// DeleteStageAndCommit appends ganttchart to the model stage and commit to the orm repo
func (ganttchart *GanttChart) DeleteStageAndCommit() *GanttChart {
	ganttchart.Unstage()
	DeleteORMGanttChart(ganttchart)
	return ganttchart
}

// StageCopyAndCommit appends a copy of ganttchart to the model stage and commit to the orm repo
func (ganttchart *GanttChart) StageCopyAndCommit() *GanttChart {
	_ganttchart := new(GanttChart)
	*_ganttchart = *ganttchart
	_ganttchart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMGanttChart(ganttchart)
	}
	return _ganttchart
}

// CreateORMGanttChart enables dynamic staging of a GanttChart instance
func CreateORMGanttChart(ganttchart *GanttChart) {
	ganttchart.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMGanttChart(ganttchart)
	}
}

// DeleteORMGanttChart enables dynamic staging of a GanttChart instance
func DeleteORMGanttChart(ganttchart *GanttChart) {
	ganttchart.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMGanttChart(ganttchart)
	}
}

func (stage *StageStruct) getRessourceOrderedStructWithNameField() []*Ressource {
	// have alphabetical order generation
	ressourceOrdered := []*Ressource{}
	for ressource := range stage.Ressources {
		ressourceOrdered = append(ressourceOrdered, ressource)
	}
	sort.Slice(ressourceOrdered[:], func(i, j int) bool {
		return ressourceOrdered[i].Name < ressourceOrdered[j].Name
	})
	return ressourceOrdered
}

// Stage puts ressource to the model stage
func (ressource *Ressource) Stage() *Ressource {
	Stage.Ressources[ressource] = __member
	return ressource
}

// Unstage removes ressource off the model stage
func (ressource *Ressource) Unstage() *Ressource {
	delete(Stage.Ressources, ressource)
	return ressource
}

// commit ressource to the back repo (if it is already staged)
func (ressource *Ressource) Commit() *Ressource {
	if _, ok := Stage.Ressources[ressource]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitRessource(ressource)
		}
	}
	return ressource
}

// Checkout ressource to the back repo (if it is already staged)
func (ressource *Ressource) Checkout() *Ressource {
	if _, ok := Stage.Ressources[ressource]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutRessource(ressource)
		}
	}
	return ressource
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of ressource to the model stage
func (ressource *Ressource) StageCopy() *Ressource {
	_ressource := new(Ressource)
	*_ressource = *ressource
	_ressource.Stage()
	return _ressource
}

// StageAndCommit appends ressource to the model stage and commit to the orm repo
func (ressource *Ressource) StageAndCommit() *Ressource {
	ressource.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMRessource(ressource)
	}
	return ressource
}

// DeleteStageAndCommit appends ressource to the model stage and commit to the orm repo
func (ressource *Ressource) DeleteStageAndCommit() *Ressource {
	ressource.Unstage()
	DeleteORMRessource(ressource)
	return ressource
}

// StageCopyAndCommit appends a copy of ressource to the model stage and commit to the orm repo
func (ressource *Ressource) StageCopyAndCommit() *Ressource {
	_ressource := new(Ressource)
	*_ressource = *ressource
	_ressource.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMRessource(ressource)
	}
	return _ressource
}

// CreateORMRessource enables dynamic staging of a Ressource instance
func CreateORMRessource(ressource *Ressource) {
	ressource.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMRessource(ressource)
	}
}

// DeleteORMRessource enables dynamic staging of a Ressource instance
func DeleteORMRessource(ressource *Ressource) {
	ressource.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMRessource(ressource)
	}
}

func (stage *StageStruct) getTaskOrderedStructWithNameField() []*Task {
	// have alphabetical order generation
	taskOrdered := []*Task{}
	for task := range stage.Tasks {
		taskOrdered = append(taskOrdered, task)
	}
	sort.Slice(taskOrdered[:], func(i, j int) bool {
		return taskOrdered[i].Name < taskOrdered[j].Name
	})
	return taskOrdered
}

// Stage puts task to the model stage
func (task *Task) Stage() *Task {
	Stage.Tasks[task] = __member
	return task
}

// Unstage removes task off the model stage
func (task *Task) Unstage() *Task {
	delete(Stage.Tasks, task)
	return task
}

// commit task to the back repo (if it is already staged)
func (task *Task) Commit() *Task {
	if _, ok := Stage.Tasks[task]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CommitTask(task)
		}
	}
	return task
}

// Checkout task to the back repo (if it is already staged)
func (task *Task) Checkout() *Task {
	if _, ok := Stage.Tasks[task]; ok {
		if Stage.BackRepo != nil {
			Stage.BackRepo.CheckoutTask(task)
		}
	}
	return task
}

//
// Legacy, to be deleted
//

// StageCopy appends a copy of task to the model stage
func (task *Task) StageCopy() *Task {
	_task := new(Task)
	*_task = *task
	_task.Stage()
	return _task
}

// StageAndCommit appends task to the model stage and commit to the orm repo
func (task *Task) StageAndCommit() *Task {
	task.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMTask(task)
	}
	return task
}

// DeleteStageAndCommit appends task to the model stage and commit to the orm repo
func (task *Task) DeleteStageAndCommit() *Task {
	task.Unstage()
	DeleteORMTask(task)
	return task
}

// StageCopyAndCommit appends a copy of task to the model stage and commit to the orm repo
func (task *Task) StageCopyAndCommit() *Task {
	_task := new(Task)
	*_task = *task
	_task.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMTask(task)
	}
	return _task
}

// CreateORMTask enables dynamic staging of a Task instance
func CreateORMTask(task *Task) {
	task.Stage()
	if Stage.AllModelsStructCreateCallback != nil {
		Stage.AllModelsStructCreateCallback.CreateORMTask(task)
	}
}

// DeleteORMTask enables dynamic staging of a Task instance
func DeleteORMTask(task *Task) {
	task.Unstage()
	if Stage.AllModelsStructDeleteCallback != nil {
		Stage.AllModelsStructDeleteCallback.DeleteORMTask(task)
	}
}

// swagger:ignore
type AllModelsStructCreateInterface interface { // insertion point for Callbacks on creation
	CreateORMDependency(Dependency *Dependency)
	CreateORMGanttChart(GanttChart *GanttChart)
	CreateORMRessource(Ressource *Ressource)
	CreateORMTask(Task *Task)
}

type AllModelsStructDeleteInterface interface { // insertion point for Callbacks on deletion
	DeleteORMDependency(Dependency *Dependency)
	DeleteORMGanttChart(GanttChart *GanttChart)
	DeleteORMRessource(Ressource *Ressource)
	DeleteORMTask(Task *Task)
}

func (stage *StageStruct) Reset() { // insertion point for array reset
	stage.Dependencys = make(map[*Dependency]struct{}, 0)
	stage.GanttCharts = make(map[*GanttChart]struct{}, 0)
	stage.Ressources = make(map[*Ressource]struct{}, 0)
	stage.Tasks = make(map[*Task]struct{}, 0)
}

func (stage *StageStruct) Nil() { // insertion point for array nil
	stage.Dependencys = nil
	stage.GanttCharts = nil
	stage.Ressources = nil
	stage.Tasks = nil
}
