// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"
	"time"

	"github.com/fullstack-lang/gonggooglecharts/go/models"
	"github.com/fullstack-lang/gonggooglecharts/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// declaration in order to justify use of the models import
var __Dependency__dummysDeclaration__ models.Dependency
var __Dependency_time__dummyDeclaration time.Duration

// An DependencyID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getDependency updateDependency deleteDependency
type DependencyID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// DependencyInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postDependency updateDependency
type DependencyInput struct {
	// The Dependency to submit or modify
	// in: body
	Dependency *orm.DependencyAPI
}

// GetDependencys
//
// swagger:route GET /dependencys dependencys getDependencys
//
// Get all dependencys
//
// Responses:
//    default: genericError
//        200: dependencyDBsResponse
func GetDependencys(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var dependencys []orm.DependencyDB
	query := db.Find(&dependencys)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// for each dependency, update fields from the database nullable fields
	for idx := range dependencys {
		dependency := &dependencys[idx]
		_ = dependency
		// insertion point for updating fields
		if dependency.Name_Data.Valid {
			dependency.Name = dependency.Name_Data.String
		}

	}

	c.JSON(http.StatusOK, dependencys)
}

// PostDependency
//
// swagger:route POST /dependencys dependencys postDependency
//
// Creates a dependency
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: dependencyDBResponse
func PostDependency(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.DependencyAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create dependency
	dependencyDB := orm.DependencyDB{}
	dependencyDB.DependencyAPI = input
	// insertion point for nullable field set
	dependencyDB.Name_Data.String = input.Name
	dependencyDB.Name_Data.Valid = true

	query := db.Create(&dependencyDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, dependencyDB)
}

// GetDependency
//
// swagger:route GET /dependencys/{ID} dependencys getDependency
//
// Gets the details for a dependency.
//
// Responses:
//    default: genericError
//        200: dependencyDBResponse
func GetDependency(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get dependency in DB
	var dependency orm.DependencyDB
	if err := db.First(&dependency, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// insertion point for fields value set from nullable fields
	if dependency.Name_Data.Valid {
		dependency.Name = dependency.Name_Data.String
	}

	c.JSON(http.StatusOK, dependency)
}

// UpdateDependency
//
// swagger:route PATCH /dependencys/{ID} dependencys updateDependency
//
// Update a dependency
//
// Responses:
//    default: genericError
//        200: dependencyDBResponse
func UpdateDependency(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var dependencyDB orm.DependencyDB

	// fetch the dependency
	query := db.First(&dependencyDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.DependencyAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	// insertion point for nullable field set
	input.Name_Data.String = input.Name
	input.Name_Data.Valid = true

	query = db.Model(&dependencyDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	// return status OK with the marshalling of the the dependencyDB
	c.JSON(http.StatusOK, dependencyDB)
}

// DeleteDependency
//
// swagger:route DELETE /dependencys/{ID} dependencys deleteDependency
//
// Delete a dependency
//
// Responses:
//    default: genericError
func DeleteDependency(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var dependencyDB orm.DependencyDB
	if err := db.First(&dependencyDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&dependencyDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
